CC      = gcc
CFLAGS  = -g
RM      = rm -f

# Grupo 14 Estructura de Datos y Algoritmos 26-03-21
# Andres Guevara
# Matias Hermosilla
# Esteban Hernández

default: all
all: main

main: app1.c 
	$(CC) $(CFLAGS) -o app1 app1.c

clean veryclean: 
	$(RM) main